# Generated by Django 4.2.3 on 2023-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
