# Generated by Django 4.2.3 on 2023-07-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='creatrted',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='technicians',
            old_name='destination',
            new_name='designation',
        ),
    ]
