# Generated by Django 4.2.3 on 2023-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_creatrted_contact_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('quality', models.CharField(max_length=50)),
                ('extra_idea', models.TextField()),
                ('support_time', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
