# Generated by Django 4.2.3 on 2023-08-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_servicebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
