# Generated by Django 4.2.3 on 2023-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='telegram',
            field=models.CharField(max_length=100),
        ),
    ]
